---
image: "vito-docker.artifactory.vgt.vito.be/openeo-geotrellis-kube"
imageVersion: "latest"
jmxExporterJar: "/opt/jmx_prometheus_javaagent-0.13.0.jar"
mainApplicationFile: "local:///opt/openeo/lib64/python3.8/site-packages/openeogeotrellis/deploy/kube.py"
rbac:
  serviceAccountDriver: "{{ openeo_spark_jobs_serviceaccount }}"
volumes:
  - name: "eodata"
    hostPath:
      path: "/eodata"
      type: "DirectoryOrCreate"
  - name: "layercatalog"
    configMap:
      name: layercatalog
      items:
      - key: cscale_layercatalog
        path: cscale_layercatalog.json
volumeMounts:
  - name: "eodata"
    mountPath: "/eodata"
  - name: "layercatalog"
    mountPath: /etc/config
executor:
  memory: "512m"
  cpu: 1
  envVars:
    OPENEO_CATALOG_FILES: "/etc/config/cscale_layercatalog.json"
    OPENEO_S1BACKSCATTER_ELEV_GEOID: "/opt/openeo-vito-aux-data/egm96.grd"
    OTB_HOME: "/opt/orfeo-toolbox"
    OTB_APPLICATION_PATH: "/opt/orfeo-toolbox/lib/otb/applications"
    KUBE: "true"
    GDAL_NUM_THREADS: "2"
    PYTHONPATH: "$PYTHONPATH:/opt/openeo/lib/python3.8/site-packages/"
  javaOptions: "-Dlog4j.configuration=/opt/log4j.properties -Dscala.concurrent.context.numThreads=4 -Dscala.concurrent.context.maxThreads=4"
driver:
  memory: "512m"
  cpu: 1
  envVars:
    KUBE: "true"
    KUBE_OPENEO_API_PORT: "50001"
    DRIVER_IMPLEMENTATION_PACKAGE: "openeogeotrellis"
    OPENEO_CATALOG_FILES: "/etc/config/cscale_layercatalog.json"
    OPENEO_S1BACKSCATTER_ELEV_GEOID: "/opt/openeo-vito-aux-data/egm96.grd"
    OTB_HOME: "/opt/orfeo-toolbox"
    OTB_APPLICATION_PATH: "/opt/orfeo-toolbox/lib/otb/applications"
    PYTHONPATH: "$PYTHONPATH:/opt/openeo/lib/python3.8/site-packages/"
    TRAVIS: 1
  javaOptions: "-Dlog4j.configuration=/opt/log4j.properties -Dscala.concurrent.context.numThreads=6 -Dpixels.treshold=1000000"
sparkConf:
  "spark.executorEnv.DRIVER_IMPLEMENTATION_PACKAGE": "openeogeotrellis"
  "spark.extraListeners": "org.openeo.sparklisteners.CancelRunawayJobListener"
  "spark.appMasterEnv.DRIVER_IMPLEMENTATION_PACKAGE": "openeogeotrellis"
  "spark.executorEnv.GDAL_NUM_THREADS": "2"
  "spark.executorEnv.GDAL_DISABLE_READDIR_ON_OPEN": "EMPTY_DIR"
jarDependencies:
  - 'local:///opt/geotrellis-extensions-2.3.0_2.12-SNAPSHOT.jar'
  - 'local:///opt/geotrellis-backend-assembly-0.4.6-openeo_2.12.jar'
fileDependencies:
  - 'local:///etc/config/cscale_layercatalog.json'
service:
  enabled: true
  port: 50001
